### ISSUE TITLE
Doesn't work on localhost

### ISSUE THREAD

**Issue by e-oz** [push-based/ngx-fast-svg#60]
Angular's Express (ng serve) returns 304, not 200, and apparently, it breaks something - an icon is not rendered (completely empty). Only the suspense image is visible for a moment.
The path to the icon is correct (and redirected response contains the SVG body).
Angular 16.2

**Comment by ChristopherPHolder** [comment]
Hi @e-oz Can you please provided a reprodusable example or explain in more detail what you have tried?

**Comment by e-oz** [comment]
Sure: https://stackblitz.com/edit/stackblitz-starters-ltryjg?file=src%2Fmain.ts

**Comment by ChristopherPHolder** [comment]
Thanks @e-oz 

https://stackblitz.com/edit/stackblitz-starters-sbufwp

So i have made the appropriate changes and is seems to be working :D 

- you need to provideFastSVG  in bootstrapApplication. 
https://github.com/push-based/ngx-fast-svg#setup-the-library-in-your-standalone-application

- you need to expose the svg assets and map to them 

`url: (name: string) => `path/to/svg-assets/${name}.svg`

And in your angular.json
```
"architect": {
  "build": {
    "options": {
      "assets": ["src/assets"],
     }
   }
}
```

**Comment by e-oz** [comment]
thank you, and sorry for wasting your time for nothing.
